port: 7890
allow-lan: true
mode: rule
log-level: info
unified-delay: true
global-client-fingerprint: chrome
ipv6: false
profile:
  store-selected: true
  store-fake-ip: true

# 域名嗅探
sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true

dns:
  enable: true
  prefer-h3: true
  ipv6: false
  listen: 0.0.0.0:1053
  use-hosts: true
  fake-ip-range: 28.0.0.1/8
  enhanced-mode: fake-ip
  fake-ip-filter:
    - '*.lan'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    # Apple
    - 'swscan.apple.com'
    - 'mesu.apple.com'
    - 'swquery.apple.com'
    - 'swdownload.apple.com'
    - 'swcdn.apple.com'
    - 'swdist.apple.com'
    # Microsoft Service
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - 'xbox.*.microsoft.com'
    - 'xbox.*.*.microsoft.com'
    - '+.xboxlive.com'
    #  NTP Service
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'
    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'
    - 'ntp.*.com'
    - 'ntp.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '+.pool.ntp.org'
    - 'time1.cloud.tencent.com'
    # Google
    - 'lens.l.google.com'
    # Music Service
    - '+.music.163.com'
    - '+.126.net'
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    - '*.kuwo.cn'
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    - '+.y.qq.com'
    - '+.music.tc.qq.com'
    - 'aqqmusic.tc.qq.com'
    - '+.stream.qqmusic.qq.com'
    - '+.xiami.com'
    - '+.music.migu.cn'
    # Game Service
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'
    - '+.srv.nintendo.net'
    - '*.n.n.srv.nintendo.net'
    - '+.stun.playstation.net'
    - '+.battlenet.com.cn'
    - '+.wotgame.cn'
    - '+.wggames.cn'
    - '+.wowsgame.cn'
    - '+.wargaming.net'
    - '*.square-enix.com'
    - '*.finalfantasyxiv.com'
    - '*.ffxiv.com'
    - '*.ff14.sdo.com'
    - 'ff.dorado.sdo.com'
    # Other
    - 'localhost.ptlogin2.qq.com'
    - 'localhost.sec.qq.com'
    - 'proxy.golang.org'
    - '+.qq.com'
    - '+.baidu.com'
    - '+.163.com'
    - '+.126.net'
    - '+.taobao.com'
    - '+.jd.com'
    - '+.tmall.com'
    - '*.mcdn.bilivideo.cn'
    - '+.nvidia.com'
    - '+.nvidia.cn'
    - '+.nvgs.nvidia.com'
    - '+.nvgs.nvidia.cn'
    - 'shark007.net'
    - 'assouth.p.g-tun.com'
    - 'zinc.cloud.cupronickel.goog'
    - 'brass.cloud.cupronickel.goog'
    - 'subscriptionsmobile-pa.googleapis.com'
    - 'phosphor-pa.googleapis.com'
    - 'beryllium-pa.googleapis.com'
    - 'scone-pa.googleapis.com'
    - 'na4.p.g-tun.com'
  default-nameserver:
    - 223.5.5.5
    - 1.1.1.1
    - 8.8.8.8
    - '[2402:4e00::]'
    - '[2400:3200::1]'
  nameserver:
    - 'tls://8.8.4.4#dns'
    - 'tls://1.0.0.1#dns'
    - 'tls://[2001:4860:4860::8844]#dns'
    - 'tls://[2606:4700:4700::1001]#dns'
  fallback:   
    - 'tls://8.8.4.4:853#🚀'
  proxy-server-nameserver:
    - https://doh.pub/dns-query
