name: Pull Specific Files

on:
  schedule:
    - cron: '0 0 * * *'  # 设置你想要触发的定时，比如每天
  workflow_dispatch:  # 添加手动触发的事件

jobs:
  pull-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          repository: ACL4SSR/ACL4SSR  # 指定要拉取的远程仓库
          ref: master  # 指定要拉取的分支为 master

      - name: Pull specific files from other repository
        run: |
          mkdir -p rule/reject
          curl -LJO https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml -o rule/reject/BanAD.yaml
          curl -LJO https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanProgramAD.yaml -o rule/reject/BanProgramAD.yaml
          # 下载特定文件，并将其放置到你想要的目标文件夹

      - name: Commit changes
        run: |
          git config user.email "your.email@example.com"
          git config user.name "xyself"
          git add .
          git commit -m "Pulling specific files from other repository"

      - name: Push changes
        run: |
          git push  # 推送到当前仓库的 master 分支
