name: Pull Files from ACL4SSR

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 16 */3 * *'  # 每3天的中国时间晚上12点执行任务
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pull-files:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3  # 更新到v3版本

      - name: Download Files
        run: |
          mkdir -p rule/proxy rule/reject 
          curl -o rule/PrivateTracker.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrivateTracker/PrivateTracker.list
          curl -o rule/PrivateTracker.yaml https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrivateTracker/PrivateTracker.yaml
          curl -o rule/reject/BanAD.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
          curl -o rule/reject/BanAD.yaml https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml
          curl -o rule/reject/BanEasyListChina.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
          curl -o rule/reject/BanEasyListChina.yaml https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyListChina.yaml
          curl -o rule/reject/BanProgramAD.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
          curl -o rule/reject/BanProgramAD.yaml https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanProgramAD.yaml

      - name: Configure Git
        run: |
          git config user.email "133769218+xyself@users.noreply.github.com"
          git config user.name "xyself"

      - name: Commit files
        run: |
          git add rule/PrivateTracker.list rule/PrivateTracker.yaml rule/reject/BanAD.list rule/reject/BanAD.yaml \
          rule/reject/BanEasyListChina.list rule/reject/BanEasyListChina.yaml rule/reject/BanProgramAD.list rule/reject/BanProgramAD.yaml
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-pull updated files"
          
      - name: Push changes
        run: git push origin HEAD:master
