name: Pull Files from ACL4SSR

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 16 */3 * *'  # 每3天的中国时间晚上12点执行任务
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pull-files:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Download Files
        run: |
          mkdir -p rule/direct rule/proxy rule/reject rule/fakeip

          # fake yaml
          curl -o rule/fakeip/fakeip-filter.mrs https://raw.githubusercontent.com/DustinWin/ruleset_geodata/raw/clash-ruleset/fakeip-filter.mrs
          # direct yaml
          # proxy yaml
          curl -o rule/proxy/telegramip.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs
          curl -o rule/proxy/telegram.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs
          curl -o rule/proxy/ProxyMedia.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
          curl -o rule/proxy/ProxyMedia.yaml https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyMedia.yaml

          curl -o rule/proxy/Blizzard.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Blizzard/Blizzard.list
          curl -o rule/proxy/Blizzard.yaml https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Blizzard/Blizzard_No_Resolve.yaml
          # reject yaml
          curl -o rule/reject/BanAD.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
          curl -o rule/reject/BanAD.yaml https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml
          curl -o rule/reject/BanEasyListChina.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
          curl -o rule/reject/BanEasyListChina.yaml https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyListChina.yaml
          curl -o rule/reject/BanProgramAD.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
          curl -o rule/reject/BanProgramAD.yaml https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanProgramAD.yaml

      - name: Configure Git
        run: |
          git config user.email "133769218+xyself@users.noreply.github.com"
          git config user.name "xyself"

      - name: Commit files
        run: |
          git add rule/reject rule/direct rule/proxy
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-pull updated files"
      - name: Push changes
        run: git push origin HEAD:master
